create table if not exists trade_dna (id uuid default gen_random_uuid() primary key, ticker text, entry_price float, exit_price float, return_pct float, profitable boolean, catalyst text, signal_score int, reason text, signal_type text, sector text, factor_breakdown jsonb, agent_votes jsonb, holding_period_days float, confidence int, risk_score int, is_crypto boolean default false, market_conditions text, vix_at_entry float, created_at timestamptz default now());
create table if not exists decision_log (id uuid default gen_random_uuid() primary key, type text, message text, ticker text, signal_score int, confidence int, dollars float, pnl_pct float, catalyst text, thesis text, agent_votes jsonb, factor_breakdown jsonb, risk_score int, is_crypto boolean, created_at timestamptz default now());
create table if not exists active_signals (id uuid default gen_random_uuid() primary key, ticker text unique, signal text, type text, signal_score int, confidence int, catalyst text, detail text, thesis text, target_price float, stop_loss float, expected_return text, timeframe text, factor_breakdown jsonb, conviction jsonb, risk_score int, is_crypto boolean, found_at timestamptz, updated_at timestamptz default now());
create table if not exists pending_queue (id uuid default gen_random_uuid() primary key, ticker text unique, signal text, dollars float, signal_score int, confidence int, catalyst text, thesis text, queued_at text, is_crypto boolean, created_at timestamptz default now());
create table if not exists influencer_alerts (id uuid default gen_random_uuid() primary key, person text, platform text, action text, related_tickers text[], estimated_impact text, confidence int, sentiment text, urgency text, trading_implication text, created_at timestamptz default now());
create table if not exists earnings_calendar (id uuid default gen_random_uuid() primary key, ticker text, company_name text, report_date date, report_time text, eps_estimate float, eps_actual float, revenue_estimate bigint, revenue_actual bigint, surprise_pct float, created_at timestamptz default now());
create table if not exists agent_performance (id uuid default gen_random_uuid() primary key, agent_name text, ticker text, vote text, signal_score int, outcome text, return_pct float, was_correct boolean, created_at timestamptz default now());
create table if not exists similarity_cache (id uuid default gen_random_uuid() primary key, ticker text, signal_type text, similar_count int, win_rate float, avg_return float, best_return float, worst_return float, avg_hold_days float, similarity_score float, computed_at timestamptz default now());
create table if not exists signal_memory (id uuid default gen_random_uuid() primary key, ticker text, signal text, signal_score int, confidence int, catalyst text, risk_score int, disposition text, reason text, agent_votes jsonb, conviction_probability int, technical_score int, market_regime text, is_crypto boolean default false, found_at timestamptz, recorded_at timestamptz default now());
alter table trade_dna add column if not exists signal_type text;
alter table trade_dna add column if not exists sector text;
alter table trade_dna add column if not exists factor_breakdown jsonb;
alter table trade_dna add column if not exists agent_votes jsonb;
alter table trade_dna add column if not exists holding_period_days float;
alter table trade_dna add column if not exists confidence int;
alter table trade_dna add column if not exists risk_score int;
alter table trade_dna add column if not exists is_crypto boolean default false;
alter table trade_dna add column if not exists market_conditions text;
alter table trade_dna add column if not exists vix_at_entry float;
create index if not exists idx_trade_dna_ticker on trade_dna(ticker);
create index if not exists idx_trade_dna_signal_type on trade_dna(signal_type);
create index if not exists idx_decision_log_type on decision_log(type);
create index if not exists idx_agent_performance_agent on agent_performance(agent_name);
create index if not exists idx_earnings_calendar_date on earnings_calendar(report_date);
create index if not exists idx_signal_memory_disposition on signal_memory(disposition);
create index if not exists idx_signal_memory_ticker on signal_memory(ticker);
